name: Eleventy build production Pantheon WP 5.8.1
# site:  test.cannabis.ca.gov
# editor: https://test-cannabis-ca-gov.pantheonsite.io
# s3 bucket http://test.cannabis.ca.gov.s3-website-us-west-1.amazonaws.com/
on:
  push:
    branches:
      - test
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Build 11ty
        run: |
          mkdir dist
          npm install
          npm run build:test
          npm run test:setup

      # deploy built files to separate branch that contains only built files that github pages uses to serve site
      - name: Deploy to github pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: deploy_test
      # Push built site files to S3 production bucket    
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'test.cannabis.ca.gov'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: ./docs # only move built directory

      # Reset the cache-control headers on static assets on production S3 bucket
      - name: Reset cache-control on static files
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-west-1'   # optional: defaults to us-east-1
          source: './docs/fonts'
          dest: 's3://test.cannabis.ca.gov/fonts'
          flags: --recursive --cache-control max-age=15552000

      # - name: Deploy redirects
      #   run: |
      #     AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run deploy:redirects

      # # Invalidate Cloudfront production distribution
      # - name: invalidate
      #   uses: chetan/invalidate-cloudfront-action@v1.3
      #   env:
      #     DISTRIBUTION: 'E1HY53GZXHPHRV'
      #     PATHS: '/*'
      #     AWS_REGION: 'us-west-1'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    


